app.name=ProfileEnvironment
app.version=1.0.0
server.port=6161
app.activated.server=prod
# spring.profiles.active=prod - hardcode the profile in the application-prod.properties file, so it will be used when this profile is active